### ISSUE TITLE
Soucis avec l'affichage des prix dans le menu interractif

### ISSUE THREAD

**Issue by IamKicchi** [SPEED0U/StarCitizenFrenchTranslation#20]
Bonjour,

L'affichage de la valeur des prix (le chiffre) en mode interactif (quand on utilise la touche F) pour acheter quelque chose ne s'affiche pas.
Je m'en suis rendu compte avec cette ligne : ui_shop_quickBuy=Achat rapide - ~shopInteractionData(prix) UEC
Il semble que se soit le seul endroit ou l'appel de cette fonction est fait dans la traduction actuellement disponible lors de la rédaction de cette issue.

Le screen, car un schéma veux mieux qu'un long discours :
![ScreenShot-2023-10-18_18-48-50-0B6](https://github.com/SPEED0U/StarCitizenFrenchTranslation/assets/73335983/079da07d-5db4-400c-bebf-bd978637559e)

J'espère avoir été clair 👍🏼

**Comment by SPEED0U** [comment]
Merci, c'est fixé pour la prochaine version!
