### ISSUE TITLE
[Demande] Script universel pour les traductions française

### ISSUE THREAD

**Issue by Luna664** [SPEED0U/StarCitizenFrenchTranslation#23]
Bonjour, j'ai pour projet de regroupé toute les traductions françaises dans un seul et même script pour que tout le monde s'y retrouve plus facilement sans forcement galéré à cherché sur google/youtube.

J'aimerais donc avoir l'autorisation de me servir de votre script install_fr.ps1 comme base pour pouvoir réalisé mon projet, j'ai déjà fait une petite ébauche que je garde pour mon utilisation privé, si vous voulez je serais très heureuse de vous l'envoyer via Discord (Lune664) ou même directement ici si vous voulez y jeter un œil avant de prendre une décision.

**Comment by Alayan10** [comment]
Il me semble que ça existe déjà https://github.com/Dymerz/StarCitizen-Localization
