### ISSUE TITLE
Commits Vides Automatisés

### ISSUE THREAD

**Issue by Alayan10** [SPEED0U/StarCitizenFrenchTranslation#28]
@SPEED0U J'ai remarqué que ton repo **génère des commits vides automatiquement toutes les heures...** De mon point de vue, ça a tout l'air d'une technique malhonnête pour faire gonfler artificiellement les statistiques de ton dépôt et de tromper les visiteurs.
Y a t-il une raison particulière à cela ?

**Comment by SPEED0U** [comment]
Oui c'est pour migrer les changements fais sur le site directement sur ce répo, si il y'a une automatisation toutes les heures c'est pour mettre à jour le fichier, et celà se fait même si il n'y a pas de changements. C'est une limitation que j'ai pour le moment.

Honnêtement je m'en fou des stats, je fais ça pour automatiser les taches pour que tout le monde ait les mises à jour dès que possible.
